# Generated by Django 2.2.5 on 2019-09-29 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_clientprofile_company_staffprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffprofile',
            old_name='othername',
            new_name='other_name',
        ),
    ]
